name: office 365
pipeline:
  - name: json_event
    external:
      name: json.parse-json
  - name: parse_email
    external:
      name: grok.match
      properties:
        input_field: '{{json_event.message.UserId}}'
        output_field: message
        pattern: '%{EMAILADDRESS:email}'
  - name: parse_client_ip
    external:
      name: grok.match
      properties:
        input_field: '{{json_event.message.ClientIP}}'
        output_field: result
        pattern: '::ffff:%{IP:ip}|%{IP:ip}(:%{INT:port})?'
    filter: '{{json_event.message.ClientIP != null and json_event.message.ClientIP != "" and json_event.message.ClientIP != "<null>"}}'
  - name: set_common_fields
  - name: set_office365_fields
  - name: parse_exchange
    filter: '{{json_event.message.RecordType == 2}}'
  - name: parse_network_traffic
    filter: '{{json_event.message.RecordType in [15, 25]}}'
  - name: parse_azure_active_directory_operation
    filter: '{{json_event.message.RecordType == 15}}'
  - name: parse_sharepoint_file_operation
    filter: '{{json_event.message.RecordType == 6}}'
  - name: parse_team
    filter: '{{json_event.message.RecordType == 25}}'

stages:
  set_common_fields:
    actions:
      - set:
          '@timestamp': '{{json_event.message.CreateTime}}'
          service.name: '{{json_event.message.Workload}}'
          event.action: '{{json_event.message.Operation}}'
          event.kind: 'event'
          event.code: '{{json_event.message.RecordType | string}}'
          user.name: '{{json_event.message.UserId}}'
          user.email: '{{parse_email.message.email}}'
          organization.id: '{{json_event.message.OrganizationId}}'
          action.id: '{{json_event.message.RecordType}}'
          action.name: '{{json_event.message.Operation}}'
      - set:
          action.properties: >
            [
            {% for modifiedProperty in json_event.message.ModifiedProperties %}
            {% if modifiedProperty.Name != "Included Updated Properties"%}
            {% if modifiedProperty.Value != null and modifiedProperty.Value != "<Null>"%}
            {'name': '{{modifiedProperty.Name or Null}}', 'value': '{{modifiedProperty.Value}}'},
            {% else %}
            {'name': '{{modifiedProperty.Name or Null}}', 'value': None},
            {% endif %}
            {% endif %}
            {% endfor %}
            ]
        filter: '{{json_event.message.get("ModifiedProperties", []) != []}}'
      - set:
          source.ip: '{{parse_client_ip.result.ip}}'
          source.port: '{{parse_client_ip.result.port}}'
        filter: '{{json_event.message.get("ClientIP") != None and json_event.message.ClientIP != "" and json_event.message.ClientIP != "<null>"}}'
      - set:
          action.target: 'user'
        filter: '{{json_event.message.get("UserId") != None}}'
      - translate:
        dictionary:
          'Succeeded': 'success'
          'critical': 'failure'
        mapping:
          json_event.message.ResultStatus: action.outcome
        fallback: 'success'

  set_office365_fields:
    actions:
      - set:
          office365.record_type: '{{json_event.message.RecordType}}'
          office365.result_status: '{{json_event.message.ResultStatus}}'
          office365.user_type.code: '{{json_event.message.UserType}}'
          office365.scope.code: '{{json_event.message.Scope}}'
      - translate:
        dictionary:
          0: 'Regular'
          1: 'Reserved'
          2: 'Admin'
          3: 'DcAdmin'
          4: 'System'
          5: 'Application'
          6: 'ServicePrincipal'
          7: 'CustomPolicy'
          8: 'SystemPolicy'
        mapping:
          office365.user_type.code: office365.user_type.name
      - translate:
        dictionary:
          0: 'Online'
          1: 'Onprem'
        mapping:
          office365.scope.code: office365.scope.name
        filter: '{{json_event.message.Scope != null}}'
      - set:
          office365.context.aad_session_id: '{{json_event.message.AppAccessContext.AADSessionId}}'
          office365.context.api_id: '{{json_event.message.AppAccessContext.APIId}}'
          office365.context.client.id: '{{json_event.message.AppAccessContext.ClientAppId}}'
          office365.context.client.name: '{{json_event.message.AppAccessContext.ClientAppName}}'
          office365.context.correlation.id: '{{json_event.message.AppAccessContext.CorrelationId}}'
        filter: '{{json_event.message.get("AppAccessContext") != None}}'

  parse_exchange:
    actions:
      - translate:
        dictionary:
          'MailboxLogin': '["authentication"]'
        mapping:
          event.action: event.category
        fallback: '["email", "file"]'
      - translate:
        dictionary:
          'Create': '["info", "creation"]'
          'Update': '["info", "change"]'
          'HardDelete': '["info", "deletion"]'
          'SoftDelete': '["info", "deletion"]'
          'MoveToDeletedItems': '["info", "deletion"]'
          'MailItemsAccessed': '["info"]'
          'MailboxLogin': '["start"]'
        mapping:
          event.action: event.type
        fallback: '["info"]'


  parse_network_traffic:
    actions:
      - set:
          action.target: 'network-traffic'
          event.category: ['network']
          event.type: ['info']
      - set:
          action.properties: >
            [
            {% for extendedProperty in json_event.message.ExtendedProperties %}
            {% if extendedProperty.Name != "targetIncludedUpdatedProperties"%}
            {% if extendedProperty.get("Value") != None and extendedProperty.Value != "<Null>"%}
            {'name': '{{extendedProperty.Name or Null}}', 'value': '{{extendedProperty.Value}}'},
            {% else %}
            {'name': '{{extendedProperty.Name or Null}}', 'value': None},
            {% endif %}
            {% endif %}
            {% endfor %}
            ]
        filter: '{{json_event.message.get("ExtendedProperties", []) != []}}'

  parse_azure_active_directory_operation:
    actions:
      - translate:
        dictionary:
          'UserLoggedIn': '["authentication"]'
          'UserLoginFailed': '["authentication"]'
        mapping:
          event.action: event.category
        fallback: '["iam"]'
      - translate:
        dictionary:
          'UserLoggedIn': '["start"]'
        mapping:
          event.action: event.type
        fallback: '["info"]'

  parse_sharepoint_file_operation:
    actions:
      - set:
          file.name: '{{json_event.message.SourceFileName}}'
          file.directory: '{{json_event.message.SourceRelativeUrl}}'
          event.category: ['file']
          event.type: ['info']
          user_agent.original: '{{json_event.message.UserAgent}}'
          action.outcome: 'success'
          url.full: '{{json_event.message.ObjectId}}'
          url.original: '{{json_event.message.ObjectId}}'
          action.properties: >
            [
              {
                {% if json_event.message.get("SourceFileName") != None %}"SourceFileName": "{{json_event.message.SourceFileName}}",{% endif %}
                {% if json_event.message.get("SourceRelativeUrl") != None %}"SourceRelativeUrl": "{{json_event.message.SourceRelativeUrl}}",{% endif %}
                {% if json_event.message.get("SiteUrl") != None %}"SiteUrl": "{{json_event.message.SiteUrl}}",{% endif %}
                {% if json_event.message.get("UserAgent") != None %}"UserAgent": "{{json_event.message.UserAgent}}",{% endif %}
              }
            ]

  parse_team:
    actions:
      - set:
          office365.teams.action: '{{json_event.message.Action}}'
          office365.teams.communication.type: '{{json_event.message.CommunicationType}}'
          office365.teams.channel.id: '{{json_event.message.ChannelGuid}}'
          office365.teams.channel.name: '{{json_event.message.ChannelName}}'
          office365.teams.channel.type: '{{json_event.message.ChannelType}}'
          office365.teams.message.id: '{{json_event.message.MessageId}}'
          office365.teams.message.version: '{{json_event.message.MessageVersion}}'
          office365.teams.message.size: '{{json_event.message.MessageSizeInBytes}}'
          office365.teams.message.urls: '{{json_event.message.MessageURLs}}'
          office365.teams.team.id: '{{json_event.message.TeamGuid}}'
          office365.teams.team.name: '{{json_event.message.TeamName}}'
          office365.teams.invitee: '{{json_event.message.Invitee}}'
      - set:
          office365.teams.team.members: >
            {%
              set mapping = {
                0: "Member",
                1: "Owner",
                2: "Guest"
              }
            %}[
              {%for member in json_event.message.Members %}
              {"id": "{{member.UPN}}", "role": "{{mapping.get(member.Role)}}"},
              {% endfor %}
            ]
        filter: '{{json_event.message.get("Members", []) != []}}'
