name: digital_shadows_searchlight
pipeline:
  - external:
      name: json.parse-json
      properties:
        input_field: '{{original.message}}'
        output_field: message
    name: json_event
  - name: field_extraction
stages:
  field_extraction:
    actions:
      - set:
          digital_shadows_searchlight.event.id: "{{json_event.message.id}}"
          event.kind: alert
          event.category: threat
          event.type: indicator
          event.outcome: success
          event.reason: "{{json_event.message.classification}}"
          digital_shadows_searchlight.risk_level: "{{json_event.message.get('risk-assessment').get('risk-level') or json_event.message.get('risk-level')}}"
          digital_shadows_searchlight.risk_factors: "{{json_event.message.get('risk-factors')}}"
          rule.name: "{{json_event.message.title}}"
          rule.description: "{{json_event.message.description}}"
          event.start: "{{json_event.message.raised}}"
          event.end: "{{json_event.message.updated}}"
          digital_shadows_searchlight.assignee: "{{json_event.message.assignee}}"
          digital_shadows_searchlight.portal_id: "{{ json_event.message.get('portal-id') }}"
          digital_shadows_searchlight.state: "{{json_event.message.state}}"

      - set:
          digital_shadows_searchlight.source.alert_id: "{{json_event.message.source.get('alert-id')}}"
          digital_shadows_searchlight.source.incident_id: "{{json_event.message.source.get('incident-id')}}"
        filter: "{{json_event.message.source != null}}"